application:
  host_name: unknown.domain
  engineering_email: no-reply@example.com
  enable_static_files: true
environment:
  send_email: false
  use_local_routes: false
sidekiq:
  enable_authentication: false
  username: ""
  password: ""
sentry:
  enable: false
  dsn: ""
