application:
  cors_origins: <%= ENV.fetch("CORS_ORIGINS").split(",") %>
  enable_static_files: <%= ENV.fetch("RAILS_SERVE_STATIC_FILES", "enabled") == "enabled" %>
  engineering_email: <%= ENV.fetch("ENGINEERING_EMAIL") %>
  host_name: <%= ENV.fetch("HOST_NAME") %>
sendgrid:
  address: smtp.sendgrid.net
  port: 587
  username: <%= ENV.fetch("SENDGRID_USERNAME") %>
  password: <%= ENV.fetch("SENDGRID_PASSWORD") %>
sidekiq:
  enable_authentication: true
  username: <%= ENV.fetch("SIDEKIQ_USERNAME") %>
  password: <%= ENV.fetch("SIDEKIQ_PASSWORD") %>
sentry:
  enable: true
  dsn: <%= ENV.fetch("SENTRY_DSN") %>

