server:
  enable_static_files: <%= ENV.fetch('RAILS_SERVE_STATIC_FILES', 'true') == 'true' %>
  log_to_stdout: <%= ENV.fetch('RAILS_LOG_TO_STDOUT', 'true') == 'true' %>
database:
  url: <%= ENV.fetch('DATABASE_URL') %>
