application:
  enable_static_files: <%= ENV.fetch("RAILS_SERVE_STATIC_FILES", "enabled") == "enabled" %>
  log_to_stdout: <%= ENV.fetch("RAILS_LOG_TO_STDOUT", "enabled") == "enabled" %>
database:
  url: <%= ENV.fetch("DATABASE_URL") %>
sendgrid:
  address: smtp.sendgrid.net
  port: 587
  username: <%= ENV.fetch("SENDGRID_USERNAME") %>
  password: <%= ENV.fetch("SENDGRID_PASSWORD) %>
